version: '3.1'
services:
  odoo14:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    command: --dev=all --log-handler=odoo:DEBUG
    volumes:
      - odoo14-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/tmp
    volumes:
      - odoo14-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo14-web-data:
  odoo14-db-data:

# main password for database
# mpwd = 5nqh-sycr-df64